profiles:
  active: LOCAL
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
#  mvc:
#    #    throw-exception-if-no-handler-found: true
#    static-path-pattern: /resources/**
h2:
  console:
    enabled: true
    path: /h2-console
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: none
  generate-ddl: false
  open-in-view: false
  properties:
    hibernate:
      format_sql: true
#      show_sql: true
#      use_sql_comments: true
logging:
#  file: logs
#  config: classpath:log/logback-spring.xml
  level:
    com.syshology.jpa: info
    org:
      hibernate:
        SQL: info
#        type: trace
#      com.zaxxer.hikari.HikariDataSource: trace

